### PR TITLE
Make the owner vagrant

### LINKED ISSUE #691: Mounting shares as www-data breaks core_dev extension
#663 breaks the ability to use the core_dev extension to run the WordPress core unit test suite within the virtual machine. Because the entire `wordpress-develop` directory is owned by www-data, `chmod` commands within the test suite fail when run via phpunit.

To replicate, follow the [use an existing WP checkout](https://github.com/Chassis/core_dev#use-an-existing-wordpress-checkout) instructions from the `core_dev` README, then provision your virtual machine and attempt to run 

```sh
vagrant ssh -c "cd /vagrant/wordpress-develop && phpunit --colors --filter Tests_WP_Customize_Manager"
```
to execute one specific test suite within the VM. You will see the `chown` command fail.

Tested in Vagrant 2.2.4 & 2.2.5 on an Ubuntu 19.04 host with VirtualBox 6.0.10.

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #691.

### CODE REVIEW

**Comment by BronsonQuick** [comment]
@kadamwhite Can you please test this one out for #691. I'm just spinning up a new VM to check that the logs still work with this fix. Thank you Sir!

**Comment by BronsonQuick** [comment]
Alrighty. The log fix is still working. 🎉

**Comment by BronsonQuick** [comment]
@kadamwhite Ping again for a review and test of this please! My BuddyPress Dev extension needs this fix to go in as well. Thank you Sir!

**Comment by dinhtungdu** [comment]
This PR is working well for me too! ✅

**Comment by BronsonQuick** [comment]
@dinhtungdu Awesome. Thanks so for testing that and confirming this fixes your issue too! I'll ping some of the other Chassis people for a review so we can ship this.

**Pull request merged**
