### PR TITLE
Update to 16.04 (Xenial)

### PR DESCRIPTION
**Pull request by rmccue**
⚠️ Do not merge. ⚠️ 

Pretty painless. Still investigating whether `ubuntu/xenial64` is the one we want though, `bento/ubuntu-16.04` may be better, as it contains multiple providers.

### CODE REVIEW

**Comment by rmccue** [comment]
This is practically ready to go. It does have some downsides:
* No support for PHP 5.3/5.4
* Existing extensions which register a service need to switch to systemd
* More shitty "errors": `==> default: mesg:` `==> default: ttyname failed: Inappropriate ioctl for device`

**Comment by BronsonQuick** [comment]
Hmm so I'm thinking maybe this could be a V2.0 and the existing version could be V1.0, tagged and deemed complete once the extensions are all updated to support systemd as well.

**Comment by rmccue** [comment]
> Existing extensions which register a service need to switch to systemd

Affected extensions that need updating:
* Cavalcade
* Mailcatcher
* MailHog

There may be third-party ones here too, but it's actually pretty minimal. Only things that manually create a service script are affected.

**Comment by rmccue** [comment]
This was really very painless. Updated Cavalcade and MailHog to use systemd scripts on >=15.04 (when systemd was introduced), and they're both working for me locally now.

I think we can merge this without requiring a version bump, since it's so minor. Most things simply work.

IMO, still needs some more manual testing. As a bonus, we can likely implement Docker support atop this quite easily, since upstart was our only real issue with that.

**Comment by ntwb** [comment]
Yolo, please and thank you.

Semantic versioning as a historical construct in regard to Chasis is it not?

**Comment by ntwb** [comment]
So, there's no way to edit aka decrypt the above whilst mobile so let's pretend it makes sense and move along as if there is nothing to see there #yolo

**Comment by ntwb** [comment]
With a fresh checkout of this branch I get a bunch of errors from failed dependencies:

```#!shell
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: mesg: 
==> default: ttyname failed
==> default: : 
==> default: Inappropriate ioctl for device
==> default: Notice: Compiled catalog for vagrant.local in environment production in 3.72 seconds
==> default: Notice: /Stage[main]/Mysql::Client::Install/Package[mysql_client]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[git-core]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}44e7aa974ab98260d7d013a2087f1c77'
==> default: Notice: /Stage[main]/Chassis::Hosts/Package[python-pip]/ensure: ensure changed 'purged' to 'latest'
==> default: Notice: /Stage[main]/Chassis::Hosts/Package[python-avahi]/ensure: ensure changed 'purged' to 'latest'
==> default: Notice: /Stage[main]/Chassis::Hosts/Package[avahi-daemon]/ensure: ensure changed 'purged' to 'latest'
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-common]/Apt::Setting[pref-php7.0-common]/File[/etc/apt/preferences.d/php7.0-common.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-mbstring]/Apt::Setting[pref-php7.0-mbstring]/File[/etc/apt/preferences.d/php7.0-mbstring.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-cli]/Apt::Setting[pref-php7.0-cli]/File[/etc/apt/preferences.d/php7.0-cli.pref]/ensure: created
==> default: Error: Could not find command '/usr/bin/add-apt-repository'
==> default: Error: /Stage[main]/Chassis::Php/Apt::Ppa[ppa:ondrej/php]/Exec[add-apt-repository-ppa:ondrej/php]/returns: change from notrun to 0 failed: Could not find command '/usr/bin/add-apt-repository'
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-curl]/Apt::Setting[pref-php7.0-curl]/File[/etc/apt/preferences.d/php7.0-curl.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Ppa[ppa:ondrej/php]/File[/etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/Apt::Ppa[ppa:ondrej/php]/File[/etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-gd]/Apt::Setting[pref-php7.0-gd]/File[/etc/apt/preferences.d/php7.0-gd.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-mysql]/Apt::Setting[pref-php7.0-mysql]/File[/etc/apt/preferences.d/php7.0-mysql.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-fpm]/Apt::Setting[pref-php7.0-fpm]/File[/etc/apt/preferences.d/php7.0-fpm.pref]/ensure: created
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-zip]/Apt::Setting[pref-php7.0-zip]/File[/etc/apt/preferences.d/php7.0-zip.pref]/ensure: created
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli]/ensure: created
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin]/ensure: created
==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
==> default: Notice: /Stage[main]/Chassis::Php/Apt::Pin[php7.0-xml]/Apt::Setting[pref-php7.0-xml]/File[/etc/apt/preferences.d/php7.0-xml.pref]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Package[php7.0-xml]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-xml]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-common]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-common]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-fpm]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-fpm]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-cli]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-cli]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis::Php/File[/etc/php/7.0/fpm/pool.d/www.conf]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/File[/etc/php/7.0/fpm/pool.d/www.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis::Php/File[/etc/php/7.0/fpm/php.ini]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/File[/etc/php/7.0/fpm/php.ini]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-zip]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-zip]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-mbstring]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-mbstring]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-gd]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-gd]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-curl]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-curl]: Skipping because of failed dependencies
==> default: Notice: /Package[php7.0-mysql]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[php7.0-mysql]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Apt::Update/Exec[apt_update]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Chassis::Php/Service[php7.0-fpm]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/Service[php7.0-fpm]: Skipping because of failed dependencies
==> default: Notice: /Package[nginx]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[nginx]: Skipping because of failed dependencies
==> default: Notice: /Package[sendmail]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[sendmail]: Skipping because of failed dependencies
==> default: Notice: /Package[curl]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Package[curl]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/File[/etc/nginx]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis/File[/etc/nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/File[/etc/nginx/nginx.conf]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis/File[/etc/nginx/nginx.conf]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/File[/etc/nginx/sites-enabled]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis/File[/etc/nginx/sites-enabled]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/File[/etc/nginx/sites-available]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis/File[/etc/nginx/sites-available]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/password_hash: password_hash changed '' to '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19'
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]/ensure: defined content as '{md5}f104be140b789f9ba1b8358c4b8b9ad2'
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/home/vagrant/.wp-cli]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/home/vagrant/.wp-cli]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/index.php]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/index.php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/home/vagrant/.wp-cli/config.yml]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/home/vagrant/.wp-cli/config.yml]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/vagrant/wp]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/vagrant/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/Service[nginx]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Chassis/Service[nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_user[wordpress@localhost]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_user[wordpress@localhost]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_database[wordpress]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_database[wordpress]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_grant[wordpress@localhost/wordpress.*]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Mysql_grant[wordpress@localhost/wordpress.*]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Dependency Exec[add-apt-repository-ppa:ondrej/php] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 108.13 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

This bit looks like the start and cause of the errors:
```#!bash
==> default: Error: Could not find command '/usr/bin/add-apt-repository'
==> default: Error: /Stage[main]/Chassis::Php/Apt::Ppa[ppa:ondrej/php]/Exec[add-apt-repository-ppa:ondrej/php]/returns: change from notrun to 0 failed: Could not find command '/usr/bin/add-apt-repository'
```

**Comment by rmccue** [comment]
Interesting, I was getting the same on the Docker branch, but figured it was an unrelated thing. Will patch and push momentarily.

**Comment by ntwb** [comment]
All good now 🙆‍♂️

**Comment by stuartshields** [comment]
Just tried to load extensions from config.yaml inside of content and got the following error:
```ERROR: Could not load config:
    (/Users/stuartshields/Projects/vip-test/content/config.yaml): did not find expected key while parsing a block mapping at line 17 column 1```

Once I remove the requirement to load the extensions, I have no issues. 

I'm currently testing multisite setup with my VIP extension: https://github.com/stuartshields/chassis-vip-classic

**Comment by stuartshields** [comment]
Multisite failure:

```
==> default: Running Puppet with development.pp...
==> default: mesg: 
==> default: ttyname failed
==> default: : 
==> default: Inappropriate ioctl for device
==> default: Could not retrieve fact='apt_updates', resolution='<anonymous>': can't convert nil into Integer
==> default: Could not retrieve fact='apt_security_updates', resolution='<anonymous>': can't convert nil into Integer
==> default: Error: Invalid parameter root_password on Class[Mysql::Server] at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:24 on node vip.local
==> default: Error: Invalid parameter root_password on Class[Mysql::Server] at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:24 on node vip.local

```

**Comment by stuartshields** [comment]
I'm going to do more testing tonight on the multisite failure I experienced. This time, I'm going to just change the multisite configuration in the config file.

**Comment by stuartshields** [comment]
@rmccue This dies pretty badly when I set `multisite: subdomains` and do a `vagrant up` I've changed nothing else and have added to extensions.

```
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: mesg: 
==> default: ttyname failed
==> default: : 
==> default: Inappropriate ioctl for device
==> default: Could not retrieve fact='apt_updates', resolution='<anonymous>': can't convert nil into Integer
==> default: Could not retrieve fact='apt_security_updates', resolution='<anonymous>': can't convert nil into Integer
==> default: Error: Invalid parameter root_password on Class[Mysql::Server] at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:24 on node vagrant.local
==> default: Error: Invalid parameter root_password on Class[Mysql::Server] at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:24 on node vagrant.local
```

**Comment by rmccue** [comment]
<-- forgot to update the chassis-hosts service 🤦‍♂️

**Comment by rmccue** [comment]
Subdomains should now be fixed!

**Comment by BronsonQuick** [comment]
@rmccue Nice work Sir. I can confirm subdomains are fixed! :shipit:

**Comment by katmoody** [comment]
This looked good for a bit ... but still resulted in errors. Since I'm not as familiar with this I can't be sure I didn't do something wrong on my end ;-) 

first hiccup: 
```==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory```

this resulted in an end result of: 
```==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apt at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:8 on node vagrant.local
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apt at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:8 on node vagrant.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

**Comment by katmoody** [comment]
Update. After redoing it from the command line (no laughing!) i still got errors. I ran the `git submodule update --init --recursive` and it came back with 
```Submodule path 'puppet/modules/apt': checked out '3afcc85932586aaa36913b131ef6662166f3155e'
Submodule path 'puppet/modules/mysql': checked out '9442272f5654b10d1ce33559ebb73d45ff23a128'```
After that I ran a `vagrant provision` and it completed successfully! 

Woot!

**Comment by rmccue** [comment]
@katmoody's problem above is that submodules weren't updated; filed #368 to warn the user on that one.

@BronsonQuick Your review comments are fixed now, can you re-review?

**Pull request merged**
