### PR TITLE
Fix versioncmp issue

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #419

### CODE REVIEW

**Comment by rmccue** [comment]
We need to disable the lint for this: http://puppet-lint.com/checks/only_variable_string/

**Comment by BronsonQuick** [comment]
@rmccue That check caught a bunch of other cases where we were doing that which I corrected. The `versioncmp`is the only exception to the rule seeing it needs to be a string. Could we maybe cast it so that we can keep that check?

**Comment by rmccue** [comment]
> Could we maybe cast it so that we can keep that check?

The string bit is how you cast in Puppet.

We could alternatively do it on the Ruby parsing side in `chassis.rb`.

**Comment by rmccue** [comment]
FWIW, I actually think that sniff is dangerous, because there's no other way to cast to a string in Puppet, so it's blocking valuable functionality.

**Comment by BronsonQuick** [comment]
@rmccue Updated! I guess we should tag this release too yeah?

**Comment by BronsonQuick** [comment]
Fixes in #421

**Pull request closed without merging**
