### PR TITLE
Add a conditional so extensions can override MySQL if they need to

### LINKED ISSUE #445: We need to add the ability to override mysql::server in extensions
This is related to the https://github.com/Chassis/MariaDB extensions I made this afternoon.

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #445

### CODE REVIEW

**Comment by rmccue** [comment]
This shouldn't be required. I think there are two ways to do this already; amending attributes or setting on the params class.

[Amending attributes](https://docs.puppet.com/puppet/5.1/lang_resources_advanced.html#amending-attributes-with-a-resource-reference):

```puppet
Class['mysql::server'] {
    package_name => 'mariadb-server',
    # ...
}
```

(Should be able to override everything except `root_password`)

Alternatively, since we don't declare it, you should be able to declare the `mysql::params` class:

```puppet
class mysql::params {
    server_package_name => 'mariadb-server',
    # ...
}
```

**Comment by BronsonQuick** [comment]
@rmccue Thanks for the review. I'll see if I can rework my extension based on your feedback!

**Comment by rmccue** [comment]
@BronsonQuick What's the status of this one? Can we close?

**Comment by BronsonQuick** [comment]
I couldn't get it to work so yeah I'll kill it!

**Pull request closed without merging**
