### PR TITLE
Add hosts updater config

### LINKED ISSUE #753: Add config option for vagrant hosts-updater
I had a bug report from @kucrut that Avahi doesn't work on Arch Linux so let's add a config option to use Vagrant Hosts updater as a work around.

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #753.

### CODE REVIEW

**Comment by kucrut** [comment]
Thanks @BronsonQuick!

I tested this branch on an _existing_ box and got this error:

```
>>> $ vagrant reload
==> site.local: [vagrant-hostsupdater] Removing hosts
==> site.local: Checking if box 'chassis/chassis' version '1.0.1' is up to date...
==> site.local: Clearing any previously set forwarded ports...
==> site.local: Clearing any previously set network interfaces...
==> site.local: Preparing network interfaces based on configuration...
site.local: Adapter 1: nat
site.local: Adapter 2: hostonly
==> site.local: Forwarding ports...
site.local: 80 (guest) => 8000 (host) (adapter 1)
site.local: 22 (guest) => 2222 (host) (adapter 1)
==> site.local: Running 'pre-boot' VM customizations...
==> site.local: Booting VM...
==> site.local: Waiting for machine to boot. This may take a few minutes...
site.local: SSH address: 127.0.0.1:2222
site.local: SSH username: vagrant
site.local: SSH auth method: private key
site.local: Warning: Connection reset. Retrying...
site.local: Warning: Remote connection disconnect. Retrying...
site.local: Warning: Connection reset. Retrying...
site.local: Warning: Remote connection disconnect. Retrying...
site.local: Warning: Connection reset. Retrying...
```

Steps:
* Install the hostsupdater plugin.
* Create `~/.chassis/config.yaml`.
* Add `hostsupdater: true` to the global config.
* Reload a running box.

Note that forcely stopping and bringing the box back up resulted with the same error.

**Comment by BronsonQuick** [comment]
@kucrut Can you please try this with `_mode: base` set in one of your config files? I think I've tracked it down to be an issue with the current `chassis/chassis` box. Thanks!

**Comment by BronsonQuick** [comment]
This works for me with `_mode: base` set so I'm going to try rebuilding the `chassis/chassis` box to see if it works with that as well when I've done that.

**Comment by BronsonQuick** [comment]
I tested this locally with a rebuilt base box and it's working with that as well.

**Comment by kucrut** [comment]
@BronsonQuick Can confirm that this works with `_mode: base`.

**Pull request merged**
