### PR TITLE
Update core to 4.7.3

### PR DESCRIPTION
**Pull request by cameronjonesweb**
New security and maintenance release this morning https://wordpress.org/news/2017/03/wordpress-4-7-3-security-and-maintenance-release/

### CODE REVIEW

**Comment by BronsonQuick** [comment]
@cameronjonesweb Thanks heaps for the PR! Before I merge it I just wanted to check how you updated this? Did you update the subtree?
e.g. `git subtree pull --prefix=wp --squash git@github.com:WordPress/WordPress 4.7.3` or did you just click update in the backend?

If it's the former then we're good to merge if it's the latter then it'll break the reference to the subtree. I got caught out by that before when I merged in https://github.com/Chassis/Chassis/pull/315 and it broke Chassis 😱

**Comment by cameronjonesweb** [comment]
Didn't update the subtree :( didn't know that was a thing. 
Though when I rollback and try to update the subtree it says `Working tree has modifications. Cannot add` :(

**Comment by BronsonQuick** [comment]
>Didn't update the subtree :( didn't know that was a thing.
Yeah sorry. It's a bit of a weird one. Not many people use subtrees in Git repos. It decreases the provisioning time which is why we do it.

>Working tree has modifications. Cannot add
I'll take care of it for you. Hang 10 😄  Thanks again for the PR. Most appreciated!

**Comment by BronsonQuick** [comment]
@cameronjonesweb I've pushed up a new branch and I'm just testing a fresh provision. For future reference seeing subtrees aren't used much. To update WordPress you need to delete the `wp` folder then commit that change then once that's committed you can run `git subtree add --prefix=wp --squash git@github.com:WordPress/WordPress.git 4.7.3` then push that up. I'll close this PR for now and have a new PR in a tick. Once again thanks again for being proactive! 😍

**Pull request closed without merging**
