### PR TITLE
Travis CI: Initial pass at testing Chassis install on Travis CI

### PR DESCRIPTION
**Pull request by ntwb**
Testing a basic install of Chassis on Travis CI

** DO NOT MERGE **

### CODE REVIEW

**Comment by rmccue** [comment]
My understanding was that this was impossible, since you can't run VirtualBox inside the existing VMs they have (nor inside Docker containers). If you want to explore though, good luck :)

**Comment by ntwb** [comment]
That's what I thought also, until I discovered:
> https://github.com/travis-ci/travis-ci/issues/1419#issuecomment-137728660
> If you need a full hypervisor environment, please use :
> `sudo: required`
> `services:`
> `  - docker`

Another GitHub code search revealed quite a few repos using VirtualBox and Vagrant...

**Comment by ntwb** [comment]
The OSX job failure:
```
Command: ["startvm", "3f2bce2a-893e-4aec-b522-1a565a6247d8", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

The Ubuntu job failure:
```
1.00s$ vagrant up
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
The command "vagrant up" exited with 1.
after_failure.1
0.02s$ VBoxManage --version
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (4.4.0-83-generic) or it failed to
         load. Please recompile the kernel module and install it by
           sudo /sbin/vboxconfig
         You will not be able to start VMs until this problem is fixed.
5.1.26r117224
```

The above is pretty much what I would have expected before starting this.

Time to look at a few of the repos that are using VirtualBox and Vagrant to discover how they're getting around the _virtualization_ aka `VT-x` issues

**Comment by ntwb** [comment]
Going to close this PR as @BronsonQuick is iterating on this PR in #434

**Pull request closed without merging**
