### PR TITLE
Add in new logic for version switching

### LINKED ISSUE #259: Fix version PHP version switching after initial provision
Assuming that https://github.com/Chassis/Chassis/pull/257 is merged then we will need to fix version switching.

Currently this is what happens:

1. Run `vagrant up`
2. Your Chassis box will provision correctly with Php 5.6.
3. Change the Php version in your yaml file. e.g. `7.0`
4. Run `vagrant provision`
5. All of the correct Php 7.0 modules and extensions are correctly installed.
6. Visit `http://vagrant.local/phpinfo.php`
7. You'll see that it's still on `5.6`
8. `vagrant ssh` then `sudo service stop php5.6-fpm` and `sudo service php7.0-fpm start`
9. Visit `http://vagrant.local/phpinfo.php` and you'll see the 7.0 is running.

We need to either ensure the previous version of php fpm is absent or stopped and the new version is running.

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #259 🎉

### CODE REVIEW

**Comment by BronsonQuick** [comment]
I'm doing some through testing of this now as I didn't test it well enough yesterday 👎 
- [x] 5.6 < 5.5
- [ x] 5.5 > 5.6
- [x] 5.6 < 5.4
- [ ] 5.4 > 5.6
- [x] 5.6 > 7.0
- [x] 7.0 > 7.1
- [x] 7.1 < 7.0
- [x] 7.0 < 5.6
- [x] 7.0 < 5.5
- [x] 7.0 < 5.4
- [x] 7.0 > 5.3
- [ ] 5.3 > 7.0
- [x] 5.3 > 5.4
- [ ] 5.4 > 7.1 
- [ ] 5.4 > 5.5
- [ ] 7.1 < 5.4 
- [ ] 7.0 < 5.3

**Comment by rmccue** [comment]
Going to repeat the same:

- [ ] 7.1 < 7.0
- [ ] 7.1 < 5.6
- [ ] 7.1 < 5.5
- [ ] 7.1 < 5.4
- [ ] 7.1 < 5.3
- [ ] 7.0 > 7.1
- [ ] 7.0 < 5.6
- [ ] 7.0 < 5.5
- [ ] 7.0 < 5.4
- [ ] 7.0 > 5.3
- [ ] 5.6 < 5.5
- [ ] 5.6 < 5.4
- [ ] 5.6 < 5.3
- [ ] 5.6 > 7.0
- [ ] 5.6 > 7.1
- [ ] 5.5 > 5.6
- [ ] 5.5 > 7.0
- [ ] 5.5 > 7.1
- [ ] 5.5 < 5.4
- [ ] 5.5 < 5.3
- [ ] 5.4 > 5.5
- [ ] 5.4 > 5.6
- [ ] 5.4 > 7.0
- [ ] 5.4 > 7.1
- [ ] 5.3 > 5.4
- [ ] 5.3 > 5.5
- [ ] 5.3 > 5.6
- [ ] 5.3 > 7.0
- [ ] 5.3 > 7.1

**Comment by rmccue** [comment]
@BronsonQuick Back to you for review

**Comment by BronsonQuick** [comment]
@rmccue Looks good to me Sir! Nice work! 🎉

**Pull request merged**
