### PR TITLE
PHP7

### PR DESCRIPTION
**Pull request by paulgibbs**
My first pass at PHP7 support. Important notes:
- I've never written Puppet before, so am blissfully ignorant of code standards and best practices.
- I'm unaware of code standards and best practices for Chassis itself.
- PHP 7.0 works (very basically tested -- it loaded the home page).
- Specifying PHP 5.6 ended up installing PHP 5.4, so need to fix something there.

### CODE REVIEW

**Comment by BronsonQuick** [comment]
@paulgibbs Awesome. Looks like a solid start on this. 🎈 Thanks!

**Comment by shadyvb** [comment]
Stuff that needs testing / updating from @paulgibbs : 

> - Unit testing settings from the default extensions, might need some extra libraries installed for PHP7

**Comment by paulgibbs** [comment]
The Tester extension installs the pre-7.0 version of PHPUnit. Installing the latest version of PHPUnit required a couple of extra libraries. Definitely `php7.0-zip` and I think `php7.0-dom`.

**Comment by BronsonQuick** [comment]
Alrighty. I'll have a bit of a play around with this now and see how I go. I'll be able to hunt down the missing packages we will need from my PHP7 work on Salty: https://github.com/humanmade/Salty-WordPress/blob/php7-fixes/config/salt/php7.sls#L3

I'll get those in then if I don't have too much trouble there I'll fork the Tester plugin and add some config checks and logic for PHP7.

**Comment by BronsonQuick** [comment]
Alrighty so a couple of notes for others so far.
If I `vagrant ssh` in and run `sudo apt-get install php5.5` it'll install it and `php -v` shows `5.5.38` the same goes for `5.6` and `7.0`.

Looks like `sudo apt-get install php5` doesn't work for 5.4 anymore though. I'm guessing I might need to remove all the other php packages for that to work as expected.

**Comment by BronsonQuick** [comment]
I added mbstring for Php and up here: https://github.com/Chassis/Chassis/tree/paulgibbs-php7-a I think I'll try and fix Tester next for PHP 7 then come back to debugging the PHP version switching.

**Comment by BronsonQuick** [comment]
@paulgibbs I've added `php7.0-xml` the branch https://github.com/Chassis/Chassis/tree/paulgibbs-php7-a. That gets Tester working again with PHP 7 for you. e.g.
tester-7 0

**Comment by BronsonQuick** [comment]
I'll now have a good at installing the latest version of PHPUnit and see how I go with that.

**Comment by BronsonQuick** [comment]
PHP 7 is in Chassis now: https://github.com/Chassis/Chassis/pull/257

**Pull request closed without merging**
